import 'package:flutter/material.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedvegetarischereceptenwidget/generated/GeneratedThuisgemaaktWidget11.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedvegetarischereceptenwidget/generated/GeneratedRectangle29Widget5.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedvegetarischereceptenwidget/generated/GeneratedKORSTLOZEBROCCOLIQUICHEWidget1.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedvegetarischereceptenwidget/generated/GeneratedOntbijteimuffinsWidget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedvegetarischereceptenwidget/generated/GeneratedVegetarischereceptenWidget1.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedvegetarischereceptenwidget/generated/GeneratedRectangle9Widget2.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedvegetarischereceptenwidget/generated/GeneratedRectangle10Widget1.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedvegetarischereceptenwidget/generated/GeneratedKOKOSBLOEMPANNEKOEKENWidget2.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedvegetarischereceptenwidget/generated/GeneratedRectangle11Widget1.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedvegetarischereceptenwidget/generated/GeneratedRectangle7Widget1.dart';

/* Frame Vegetarische recepten
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVegetarischereceptenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 932.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 932.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 430.0,
                              height: 82.0,
                              child: GeneratedRectangle7Widget1(),
                            ),
                            Positioned(
                              left: 118.0,
                              top: 17.0,
                              right: null,
                              bottom: null,
                              width: 249.0,
                              height: 49.0,
                              child: GeneratedThuisgemaaktWidget11(),
                            ),
                            Positioned(
                              left: 32.0,
                              top: 137.0,
                              right: null,
                              bottom: null,
                              width: 368.0,
                              height: 49.0,
                              child: GeneratedVegetarischereceptenWidget1(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 239.0,
                              right: null,
                              bottom: null,
                              width: 355.0,
                              height: 177.0,
                              child: GeneratedRectangle9Widget2(),
                            ),
                            Positioned(
                              left: 87.0,
                              top: 306.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 44.0,
                              child: GeneratedOntbijteimuffinsWidget(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 478.0,
                              right: null,
                              bottom: null,
                              width: 355.0,
                              height: 177.0,
                              child: GeneratedRectangle10Widget1(),
                            ),
                            Positioned(
                              left: 45.0,
                              top: 525.0,
                              right: null,
                              bottom: null,
                              width: 398.0,
                              height: 86.0,
                              child: GeneratedKORSTLOZEBROCCOLIQUICHEWidget1(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 704.0,
                              right: null,
                              bottom: null,
                              width: 355.0,
                              height: 177.0,
                              child: GeneratedRectangle11Widget1(),
                            ),
                            Positioned(
                              left: 47.0,
                              top: 746.0,
                              right: null,
                              bottom: null,
                              width: 350.0,
                              height: 96.0,
                              child: GeneratedKOKOSBLOEMPANNEKOEKENWidget2(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 14.0,
                              right: null,
                              bottom: null,
                              width: 68.0,
                              height: 68.0,
                              child: GeneratedRectangle29Widget5(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
