import 'package:flutter/material.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedlamgehaktballenwidget/generated/GeneratedBrownthemeatballsinoliveoilthisshouldtakeabout5minutesT.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedlamgehaktballenwidget/generated/GeneratedRectangle29Widget1.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedlamgehaktballenwidget/generated/GeneratedReclameWidget2.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedlamgehaktballenwidget/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedlamgehaktballenwidget/generated/GeneratedRectangle6Widget4.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedlamgehaktballenwidget/generated/GeneratedThuisgemaaktWidget4.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedlamgehaktballenwidget/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedlamgehaktballenwidget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedlamgehaktballenwidget/generated/GeneratedHetmakenvandezelamsgehaktballetjesiszomakkelijkScroloml.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedlamgehaktballenwidget/generated/GeneratedIngredintenJehebtmaareenpaarsimpeleingredintennodigomde.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedlamgehaktballenwidget/generated/GeneratedLAMGEHAKTBALLENWidget1.dart';

/* Frame Lam gehaktballen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLamgehaktballenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 2555.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 925.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 430.0,
                              height: 82.0,
                              child: GeneratedRectangle6Widget4(),
                            ),
                            Positioned(
                              left: 119.0,
                              top: 21.0,
                              right: null,
                              bottom: null,
                              width: 249.0,
                              height: 49.0,
                              child: GeneratedThuisgemaaktWidget4(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 92.0,
                              right: null,
                              bottom: null,
                              width: 382.0,
                              height: 96.0,
                              child: GeneratedLAMGEHAKTBALLENWidget1(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 186.0,
                              right: null,
                              bottom: null,
                              width: 304.0,
                              height: 1094.0,
                              child:
                                  GeneratedIngredintenJehebtmaareenpaarsimpeleingredintennodigomde(),
                            ),
                            Positioned(
                              left: 112.0,
                              top: 1310.0,
                              right: null,
                              bottom: null,
                              width: 205.0,
                              height: 100.0,
                              child: GeneratedRectangle15Widget(),
                            ),
                            Positioned(
                              left: 49.0,
                              top: 1468.0,
                              right: null,
                              bottom: null,
                              width: 344.0,
                              height: 340.0,
                              child:
                                  GeneratedHetmakenvandezelamsgehaktballetjesiszomakkelijkScroloml(),
                            ),
                            Positioned(
                              left: 4.0,
                              top: 1857.0,
                              right: null,
                              bottom: null,
                              width: 422.0,
                              height: 241.0,
                              child: GeneratedRectangle16Widget(),
                            ),
                            Positioned(
                              left: 4.0,
                              top: 2317.0,
                              right: null,
                              bottom: null,
                              width: 422.0,
                              height: 238.0,
                              child: GeneratedRectangle17Widget(),
                            ),
                            Positioned(
                              left: 41.0,
                              top: 2126.0,
                              right: null,
                              bottom: null,
                              width: 349.0,
                              height: 158.0,
                              child:
                                  GeneratedBrownthemeatballsinoliveoilthisshouldtakeabout5minutesT(),
                            ),
                            Positioned(
                              left: 179.0,
                              top: 1426.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 31.0,
                              child: GeneratedReclameWidget2(),
                            ),
                            Positioned(
                              left: 22.0,
                              top: 14.0,
                              right: null,
                              bottom: null,
                              width: 68.0,
                              height: 68.0,
                              child: GeneratedRectangle29Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
