import 'package:flutter/material.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedkorstlozebroccoliquichewidget/generated/GeneratedRectangle6Widget6.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedkorstlozebroccoliquichewidget/generated/GeneratedReclameWidget4.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedkorstlozebroccoliquichewidget/generated/GeneratedRectangle21Widget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedkorstlozebroccoliquichewidget/generated/GeneratedKORSTLOZEBROCCOLIQUICHEWidget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedkorstlozebroccoliquichewidget/generated/GeneratedIngredintenDeingredintenlijstvoorhetmakenvandezelekkere.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedkorstlozebroccoliquichewidget/generated/GeneratedRectangle20Widget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedkorstlozebroccoliquichewidget/generated/GeneratedThuisgemaaktWidget6.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedkorstlozebroccoliquichewidget/generated/GeneratedRectangle29Widget2.dart';

/* Frame Korstloze Broccoli Quiche
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKorstlozeBroccoliQuicheWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 2138.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 925.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 430.0,
                              height: 82.0,
                              child: GeneratedRectangle6Widget6(),
                            ),
                            Positioned(
                              left: 119.0,
                              top: 21.0,
                              right: null,
                              bottom: null,
                              width: 249.0,
                              height: 49.0,
                              child: GeneratedThuisgemaaktWidget6(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 97.0,
                              right: null,
                              bottom: null,
                              width: 434.0,
                              height: 126.0,
                              child: GeneratedKORSTLOZEBROCCOLIQUICHEWidget(),
                            ),
                            Positioned(
                              left: 10.0,
                              top: 201.0,
                              right: null,
                              bottom: null,
                              width: 406.0,
                              height: 1380.0,
                              child:
                                  GeneratedIngredintenDeingredintenlijstvoorhetmakenvandezelekkere(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 1792.0,
                              right: null,
                              bottom: null,
                              width: 404.0,
                              height: 346.0,
                              child: GeneratedRectangle20Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 1595.0,
                              right: null,
                              bottom: null,
                              width: 381.0,
                              height: 151.0,
                              child: GeneratedRectangle21Widget(),
                            ),
                            Positioned(
                              left: 176.0,
                              top: 1756.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 31.0,
                              child: GeneratedReclameWidget4(),
                            ),
                            Positioned(
                              left: 23.0,
                              top: 14.0,
                              right: null,
                              bottom: null,
                              width: 68.0,
                              height: 68.0,
                              child: GeneratedRectangle29Widget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
