import 'package:flutter/material.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedinbaconverpaktekipwidget/generated/GeneratedMakingthisrecipeissoeasyScrolldowntotherecipecardfordet.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedinbaconverpaktekipwidget/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedinbaconverpaktekipwidget/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedinbaconverpaktekipwidget/generated/GeneratedIngredintenYoullonlyneedafewsimpleingredientstomakethis.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedinbaconverpaktekipwidget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedinbaconverpaktekipwidget/generated/GeneratedNextbrushthechickenpieceswithamixtureofDijonmustardandh.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedinbaconverpaktekipwidget/generated/GeneratedRectangle28Widget1.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedinbaconverpaktekipwidget/generated/GeneratedReclameWidget1.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedinbaconverpaktekipwidget/generated/GeneratedInbaconverpaktekipWidget1.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedinbaconverpaktekipwidget/generated/GeneratedThuisgemaaktWidget3.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedinbaconverpaktekipwidget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedinbaconverpaktekipwidget/generated/GeneratedRectangle6Widget3.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedinbaconverpaktekipwidget/generated/GeneratedRoastthechickenintheovenuntilcookedthroughabout20minute.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedinbaconverpaktekipwidget/generated/GeneratedRectangle9Widget1.dart';

/* Frame In bacon verpakte kip
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInbaconverpaktekipWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 2896.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 932.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 430.0,
                              height: 82.0,
                              child: GeneratedRectangle6Widget3(),
                            ),
                            Positioned(
                              left: 119.0,
                              top: 21.0,
                              right: null,
                              bottom: null,
                              width: 249.0,
                              height: 49.0,
                              child: GeneratedThuisgemaaktWidget3(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 117.0,
                              right: null,
                              bottom: null,
                              width: 357.0,
                              height: 49.0,
                              child: GeneratedInbaconverpaktekipWidget1(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 186.0,
                              right: null,
                              bottom: null,
                              width: 304.0,
                              height: 730.0,
                              child:
                                  GeneratedIngredintenYoullonlyneedafewsimpleingredientstomakethis(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 942.0,
                              right: null,
                              bottom: null,
                              width: 306.0,
                              height: 178.0,
                              child: GeneratedRectangle9Widget1(),
                            ),
                            Positioned(
                              left: 177.0,
                              top: 1120.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 31.0,
                              child: GeneratedReclameWidget1(),
                            ),
                            Positioned(
                              left: 5.0,
                              top: 1182.0,
                              right: null,
                              bottom: null,
                              width: 425.0,
                              height: 368.0,
                              child: GeneratedRectangle11Widget(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 1574.0,
                              right: null,
                              bottom: null,
                              width: 348.0,
                              height: 210.0,
                              child:
                                  GeneratedMakingthisrecipeissoeasyScrolldowntotherecipecardfordet(),
                            ),
                            Positioned(
                              left: 5.0,
                              top: 1826.0,
                              right: null,
                              bottom: null,
                              width: 425.0,
                              height: 302.0,
                              child: GeneratedRectangle12Widget(),
                            ),
                            Positioned(
                              left: 5.0,
                              top: 2232.0,
                              right: null,
                              bottom: null,
                              width: 425.0,
                              height: 244.0,
                              child: GeneratedRectangle13Widget(),
                            ),
                            Positioned(
                              left: 5.0,
                              top: 2640.0,
                              right: null,
                              bottom: null,
                              width: 425.0,
                              height: 256.0,
                              child: GeneratedRectangle14Widget(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 2489.0,
                              right: null,
                              bottom: null,
                              width: 408.0,
                              height: 132.0,
                              child:
                                  GeneratedRoastthechickenintheovenuntilcookedthroughabout20minute(),
                            ),
                            Positioned(
                              left: 28.0,
                              top: 2151.0,
                              right: null,
                              bottom: null,
                              width: 404.0,
                              height: 54.0,
                              child:
                                  GeneratedNextbrushthechickenpieceswithamixtureofDijonmustardandh(),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 14.0,
                              right: null,
                              bottom: null,
                              width: 68.0,
                              height: 68.0,
                              child: GeneratedRectangle28Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
