import 'package:flutter/material.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedhomepagewidget/generated/GeneratedThuisgemaaktWidget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedhomepagewidget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedhomepagewidget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedhomepagewidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedhomepagewidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedhomepagewidget/generated/GeneratedWelkombijthuisgemaaktKiesuwdieetenzoekvoordeingredintdi.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedhomepagewidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedhomepagewidget/generated/GeneratedVegetarischWidget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedhomepagewidget/generated/GeneratedVleesWidget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedhomepagewidget/generated/GeneratedVeganWidget.dart';

/* Frame Homepage
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomepageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 932.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 932.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 430.0,
                              height: 82.0,
                              child: GeneratedRectangle1Widget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 22.0,
                              right: null,
                              bottom: null,
                              width: 249.0,
                              height: 49.0,
                              child: GeneratedThuisgemaaktWidget(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 112.0,
                              right: null,
                              bottom: null,
                              width: 365.0,
                              height: 110.0,
                              child: GeneratedRectangle2Widget(),
                            ),
                            Positioned(
                              left: 45.0,
                              top: 120.0,
                              right: null,
                              bottom: null,
                              width: 350.0,
                              height: 94.0,
                              child:
                                  GeneratedWelkombijthuisgemaaktKiesuwdieetenzoekvoordeingredintdi(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 252.0,
                              right: null,
                              bottom: null,
                              width: 355.0,
                              height: 177.0,
                              child: GeneratedRectangle3Widget(),
                            ),
                            Positioned(
                              left: 175.0,
                              top: 326.0,
                              right: null,
                              bottom: null,
                              width: 86.0,
                              height: 47.0,
                              child: GeneratedVleesWidget(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 463.0,
                              right: null,
                              bottom: null,
                              width: 355.0,
                              height: 177.0,
                              child: GeneratedRectangle4Widget(),
                            ),
                            Positioned(
                              left: 131.0,
                              top: 537.0,
                              right: null,
                              bottom: null,
                              width: 180.0,
                              height: 47.0,
                              child: GeneratedVegetarischWidget(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 675.0,
                              right: null,
                              bottom: null,
                              width: 355.0,
                              height: 177.0,
                              child: GeneratedRectangle5Widget(),
                            ),
                            Positioned(
                              left: 163.0,
                              top: 748.0,
                              right: null,
                              bottom: null,
                              width: 98.0,
                              height: 47.0,
                              child: GeneratedVeganWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}

mixin Overflow {}
