import 'package:flutter/material.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedeimuffinswidget/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedeimuffinswidget/generated/GeneratedInstructiesEengrootvoordeelvanditreceptisdathetzomakkel.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedeimuffinswidget/generated/GeneratedIngredintenHieriseenoverzichtvandeingredintendiejenodig.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedeimuffinswidget/generated/GeneratedThuisgemaaktWidget5.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedeimuffinswidget/generated/GeneratedONTBIJTEIMUFFINSWidget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedeimuffinswidget/generated/GeneratedRectangle19Widget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedeimuffinswidget/generated/GeneratedRectangle22Widget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedeimuffinswidget/generated/GeneratedRectangle6Widget5.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedeimuffinswidget/generated/GeneratedRectangle28Widget2.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedeimuffinswidget/generated/GeneratedReclameWidget3.dart';

/* Frame Ei muffins
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEimuffinsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        var visible;
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 2731.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 925.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 430.0,
                              height: 82.0,
                              child: GeneratedRectangle6Widget5(),
                            ),
                            Positioned(
                              left: 119.0,
                              top: 21.0,
                              right: null,
                              bottom: null,
                              width: 249.0,
                              height: 49.0,
                              child: GeneratedThuisgemaaktWidget5(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 94.0,
                              right: null,
                              bottom: null,
                              width: 305.0,
                              height: 82.0,
                              child: GeneratedONTBIJTEIMUFFINSWidget(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 186.0,
                              right: null,
                              bottom: null,
                              width: 304.0,
                              height: 678.0,
                              child:
                                  GeneratedIngredintenHieriseenoverzichtvandeingredintendiejenodig(),
                            ),
                            Positioned(
                              left: 4.0,
                              top: 1175.0,
                              right: null,
                              bottom: null,
                              width: 422.0,
                              height: 563.0,
                              child: GeneratedRectangle18Widget(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 1776.0,
                              right: null,
                              bottom: null,
                              width: 378.0,
                              height: 574.0,
                              child:
                                  GeneratedInstructiesEengrootvoordeelvanditreceptisdathetzomakkel(),
                            ),
                            Positioned(
                              left: 4.0,
                              top: 2363.0,
                              right: null,
                              bottom: null,
                              width: 421.0,
                              height: 368.0,
                              child: GeneratedRectangle19Widget(),
                            ),
                            Positioned(
                              left: 183.0,
                              top: 1134.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 31.0,
                              child: GeneratedReclameWidget3(),
                            ),
                            Positioned(
                              left: 67.0,
                              top: 889.0,
                              right: null,
                              bottom: null,
                              width: 295.0,
                              height: 219.0,
                              child: GeneratedRectangle22Widget(),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 14.0,
                              right: null,
                              bottom: null,
                              width: 68.0,
                              height: 68.0,
                              child: GeneratedRectangle28Widget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}

mixin Overflow {}
