import 'package:flutter/material.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedshiitakepaddestoelentweemanierenwidget/generated/GeneratedRectangle29Widget4.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedshiitakepaddestoelentweemanierenwidget/generated/GeneratedThuisgemaaktWidget10.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedshiitakepaddestoelentweemanierenwidget/generated/GeneratedRectangle21Widget3.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedshiitakepaddestoelentweemanierenwidget/generated/GeneratedRectangle23Widget2.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedshiitakepaddestoelentweemanierenwidget/generated/GeneratedSHIITAKEPADDESTOELENTWEEMANIERENWidget1.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedshiitakepaddestoelentweemanierenwidget/generated/GeneratedInstructiesIkbakdezechampignonsmeestalgraagindeovenHeti.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedshiitakepaddestoelentweemanierenwidget/generated/GeneratedRectangle20Widget3.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedshiitakepaddestoelentweemanierenwidget/generated/GeneratedIngredintenIkprobeerdeingredintenlijstvoormijnreceptenz.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedshiitakepaddestoelentweemanierenwidget/generated/GeneratedRectangle6Widget10.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedshiitakepaddestoelentweemanierenwidget/generated/GeneratedReclameWidget8.dart';

/* Frame SHIITAKE PADDESTOELEN: TWEE MANIEREN
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSHIITAKEPADDESTOELENTWEEMANIERENWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 2820.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 923.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 430.0,
                              height: 82.0,
                              child: GeneratedRectangle6Widget10(),
                            ),
                            Positioned(
                              left: 119.0,
                              top: 21.0,
                              right: null,
                              bottom: null,
                              width: 249.0,
                              height: 49.0,
                              child: GeneratedThuisgemaaktWidget10(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 98.0,
                              right: null,
                              bottom: null,
                              width: 434.0,
                              height: 105.0,
                              child:
                                  GeneratedSHIITAKEPADDESTOELENTWEEMANIERENWidget1(),
                            ),
                            Positioned(
                              left: 10.0,
                              top: 201.0,
                              right: null,
                              bottom: null,
                              width: 406.0,
                              height: 990.0,
                              child:
                                  GeneratedIngredintenIkprobeerdeingredintenlijstvoormijnreceptenz(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 1503.0,
                              right: null,
                              bottom: null,
                              width: 404.0,
                              height: 471.0,
                              child: GeneratedRectangle20Widget3(),
                            ),
                            Positioned(
                              left: 33.0,
                              top: 2006.0,
                              right: null,
                              bottom: null,
                              width: 383.0,
                              height: 392.0,
                              child:
                                  GeneratedInstructiesIkbakdezechampignonsmeestalgraagindeovenHeti(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 1199.0,
                              right: null,
                              bottom: null,
                              width: 381.0,
                              height: 272.0,
                              child: GeneratedRectangle21Widget3(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 2501.0,
                              right: null,
                              bottom: null,
                              width: 371.0,
                              height: 319.0,
                              child: GeneratedRectangle23Widget2(),
                            ),
                            Positioned(
                              left: 176.0,
                              top: 1467.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 31.0,
                              child: GeneratedReclameWidget8(),
                            ),
                            Positioned(
                              left: 28.0,
                              top: 14.0,
                              right: null,
                              bottom: null,
                              width: 68.0,
                              height: 68.0,
                              child: GeneratedRectangle29Widget4(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
