import 'package:flutter/material.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedgeroosterdebroccolistengelswidget/generated/GeneratedRectangle21Widget2.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedgeroosterdebroccolistengelswidget/generated/GeneratedInstructiesBroccolistengelskokeniseenvoudigScrolomlaagn.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedgeroosterdebroccolistengelswidget/generated/GeneratedReclameWidget7.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedgeroosterdebroccolistengelswidget/generated/GeneratedRectangle6Widget9.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedgeroosterdebroccolistengelswidget/generated/GeneratedRectangle20Widget2.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedgeroosterdebroccolistengelswidget/generated/GeneratedIngredintenJehebtmaareenpaarsimpeleingredintennodigomdi1.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedgeroosterdebroccolistengelswidget/generated/GeneratedThuisgemaaktWidget9.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedgeroosterdebroccolistengelswidget/generated/GeneratedGEROOSTERDEBROCCOLISTENGELSWidget1.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedgeroosterdebroccolistengelswidget/generated/GeneratedRectangle23Widget1.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedgeroosterdebroccolistengelswidget/generated/GeneratedRectangle28Widget4.dart';

import '../generatedeimuffinswidget/GeneratedEimuffinsWidget.dart';

/* Frame GEROOSTERDE BROCCOLISTENGELS
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGEROOSTERDEBROCCOLISTENGELSWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 2373.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 923.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 430.0,
                              height: 82.0,
                              child: GeneratedRectangle6Widget9(),
                            ),
                            Positioned(
                              left: 119.0,
                              top: 21.0,
                              right: null,
                              bottom: null,
                              width: 249.0,
                              height: 49.0,
                              child: GeneratedThuisgemaaktWidget9(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 97.0,
                              right: null,
                              bottom: null,
                              width: 434.0,
                              height: 126.0,
                              child:
                                  GeneratedGEROOSTERDEBROCCOLISTENGELSWidget1(),
                            ),
                            Positioned(
                              left: 10.0,
                              top: 201.0,
                              right: null,
                              bottom: null,
                              width: 406.0,
                              height: 756.0,
                              child:
                                  GeneratedIngredintenJehebtmaareenpaarsimpeleingredintennodigomdi1(),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 1219.0,
                              right: null,
                              bottom: null,
                              width: 404.0,
                              height: 346.0,
                              child: GeneratedRectangle20Widget2(),
                            ),
                            Positioned(
                              left: 37.0,
                              top: 1617.0,
                              right: null,
                              bottom: null,
                              width: 383.0,
                              height: 392.0,
                              child:
                                  GeneratedInstructiesBroccolistengelskokeniseenvoudigScrolomlaagn(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 1002.0,
                              right: null,
                              bottom: null,
                              width: 381.0,
                              height: 151.0,
                              child: GeneratedRectangle21Widget2(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 2054.0,
                              right: null,
                              bottom: null,
                              width: 371.0,
                              height: 319.0,
                              child: GeneratedRectangle23Widget1(),
                            ),
                            Positioned(
                              left: 184.0,
                              top: 1153.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 31.0,
                              child: GeneratedReclameWidget7(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 14.0,
                              right: null,
                              bottom: null,
                              width: 68.0,
                              height: 68.0,
                              child: GeneratedRectangle28Widget4(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
