import 'package:flutter/material.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedvleesreceptenwidget/generated/GeneratedRectangle28Widget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedvleesreceptenwidget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedvleesreceptenwidget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedvleesreceptenwidget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedvleesreceptenwidget/generated/GeneratedVleesreceptenWidget1.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedvleesreceptenwidget/generated/GeneratedINBACONVERPAKTEKIPWidget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedvleesreceptenwidget/generated/GeneratedLAMGEHAKTBALLENWidget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedvleesreceptenwidget/generated/GeneratedThuisgemaaktWidget1.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedvleesreceptenwidget/generated/GeneratedRectangle6Widget1.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedvleesreceptenwidget/generated/GeneratedKoreanbowlWidget.dart';

/* Frame vlees recepten
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVleesreceptenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 932.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 932.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 430.0,
                              height: 82.0,
                              child: GeneratedRectangle6Widget(),
                            ),
                            Positioned(
                              left: 118.0,
                              top: 17.0,
                              right: null,
                              bottom: null,
                              width: 249.0,
                              height: 49.0,
                              child: GeneratedThuisgemaaktWidget1(),
                            ),
                            Positioned(
                              left: 93.0,
                              top: 131.0,
                              right: null,
                              bottom: null,
                              width: 245.0,
                              height: 49.0,
                              child: GeneratedVleesreceptenWidget1(),
                            ),
                            Positioned(
                              left: 37.0,
                              top: 240.0,
                              right: null,
                              bottom: null,
                              width: 355.0,
                              height: 177.0,
                              child: GeneratedRectangle6Widget1(),
                            ),
                            Positioned(
                              left: 122.0,
                              top: 307.0,
                              right: null,
                              bottom: null,
                              width: 188.0,
                              height: 44.0,
                              child: GeneratedKoreanbowlWidget(),
                            ),
                            Positioned(
                              left: 37.0,
                              top: 479.0,
                              right: null,
                              bottom: null,
                              width: 355.0,
                              height: 177.0,
                              child: GeneratedRectangle7Widget(),
                            ),
                            Positioned(
                              left: 83.0,
                              top: 522.0,
                              right: null,
                              bottom: null,
                              width: 283.0,
                              height: 86.0,
                              child: GeneratedINBACONVERPAKTEKIPWidget(),
                            ),
                            Positioned(
                              left: 37.0,
                              top: 705.0,
                              right: null,
                              bottom: null,
                              width: 355.0,
                              height: 177.0,
                              child: GeneratedRectangle8Widget(),
                            ),
                            Positioned(
                              left: 50.0,
                              top: 747.0,
                              right: null,
                              bottom: null,
                              width: 350.0,
                              height: 96.0,
                              child: GeneratedLAMGEHAKTBALLENWidget(),
                            ),
                            Positioned(
                              left: 25.0,
                              top: 14.0,
                              right: null,
                              bottom: null,
                              width: 68.0,
                              height: 68.0,
                              child: GeneratedRectangle28Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
