import 'package:flutter/material.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedveganreceptenwidget/generated/GeneratedVeganreceptenWidget1.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedveganreceptenwidget/generated/GeneratedSHIITAKEPADDESTOELENWidget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedveganreceptenwidget/generated/GeneratedGEROOSTERDEBROCCOLISTENGELSWidget2.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedveganreceptenwidget/generated/GeneratedRectangle14Widget1.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedveganreceptenwidget/generated/GeneratedRectangle8Widget1.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedveganreceptenwidget/generated/GeneratedRectangle13Widget1.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedveganreceptenwidget/generated/GeneratedGEROOSTERDEWORTELSWidget2.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedveganreceptenwidget/generated/GeneratedRectangle12Widget1.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedveganreceptenwidget/generated/GeneratedRectangle28Widget5.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedveganreceptenwidget/generated/GeneratedThuisgemaaktWidget12.dart';

/* Frame Vegan recepten
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVeganreceptenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 932.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 932.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 430.0,
                              height: 82.0,
                              child: GeneratedRectangle8Widget1(),
                            ),
                            Positioned(
                              left: 118.0,
                              top: 17.0,
                              right: null,
                              bottom: null,
                              width: 249.0,
                              height: 49.0,
                              child: GeneratedThuisgemaaktWidget12(),
                            ),
                            Positioned(
                              left: 86.0,
                              top: 137.0,
                              right: null,
                              bottom: null,
                              width: 259.0,
                              height: 49.0,
                              child: GeneratedVeganreceptenWidget1(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 239.0,
                              right: null,
                              bottom: null,
                              width: 355.0,
                              height: 177.0,
                              child: GeneratedRectangle12Widget1(),
                            ),
                            Positioned(
                              left: 99.0,
                              top: 294.0,
                              right: null,
                              bottom: null,
                              width: 290.0,
                              height: 86.0,
                              child: GeneratedGEROOSTERDEWORTELSWidget2(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 478.0,
                              right: null,
                              bottom: null,
                              width: 355.0,
                              height: 177.0,
                              child: GeneratedRectangle13Widget1(),
                            ),
                            Positioned(
                              left: 83.0,
                              top: 542.0,
                              right: null,
                              bottom: null,
                              width: 317.0,
                              height: 98.0,
                              child:
                                  GeneratedGEROOSTERDEBROCCOLISTENGELSWidget2(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 704.0,
                              right: null,
                              bottom: null,
                              width: 355.0,
                              height: 177.0,
                              child: GeneratedRectangle14Widget1(),
                            ),
                            Positioned(
                              left: 56.0,
                              top: 746.0,
                              right: null,
                              bottom: null,
                              width: 350.0,
                              height: 96.0,
                              child: GeneratedSHIITAKEPADDESTOELENWidget(),
                            ),
                            Positioned(
                              left: 22.0,
                              top: 14.0,
                              right: null,
                              bottom: null,
                              width: 68.0,
                              height: 68.0,
                              child: GeneratedRectangle28Widget5(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
