import 'package:flutter/material.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedkoreanbowlwidget1/generated/GeneratedIngredintenJehebtmaareenpaarsimpeleingredintennodigomdi.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedkoreanbowlwidget1/generated/GeneratedRectangle29Widget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedkoreanbowlwidget1/generated/GeneratedRectangle6Widget2.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedkoreanbowlwidget1/generated/GeneratedINSTRUCTIESKoreaansrundergehaktmakeniseenvoudigScroloml.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedkoreanbowlwidget1/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedkoreanbowlwidget1/generated/GeneratedReclameWidget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedkoreanbowlwidget1/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedkoreanbowlwidget1/generated/GeneratedThuisgemaaktWidget2.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedkoreanbowlwidget1/generated/GeneratedKoreanBowlWidget.dart';

/* Frame Koreanbowl
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKoreanbowlWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 2892.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 932.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 430.0,
                              height: 82.0,
                              child: GeneratedRectangle6Widget2(),
                            ),
                            Positioned(
                              left: 119.0,
                              top: 21.0,
                              right: null,
                              bottom: null,
                              width: 249.0,
                              height: 49.0,
                              child: GeneratedThuisgemaaktWidget2(),
                            ),
                            Positioned(
                              left: 107.0,
                              top: 131.0,
                              right: null,
                              bottom: null,
                              width: 217.0,
                              height: 49.0,
                              child: GeneratedKoreanBowlWidget(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 199.0,
                              right: null,
                              bottom: null,
                              width: 304.0,
                              height: 1354.0,
                              child:
                                  GeneratedIngredintenJehebtmaareenpaarsimpeleingredintennodigomdi(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 1613.0,
                              right: null,
                              bottom: null,
                              width: 306.0,
                              height: 100.0,
                              child: GeneratedRectangle9Widget(),
                            ),
                            Positioned(
                              left: 181.0,
                              top: 1713.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 31.0,
                              child: GeneratedReclameWidget(),
                            ),
                            Positioned(
                              left: 5.0,
                              top: 1802.0,
                              right: null,
                              bottom: null,
                              width: 425.0,
                              height: 369.0,
                              child: GeneratedRectangle10Widget(),
                            ),
                            Positioned(
                              left: 55.0,
                              top: 2214.0,
                              right: null,
                              bottom: null,
                              width: 348.0,
                              height: 678.0,
                              child:
                                  GeneratedINSTRUCTIESKoreaansrundergehaktmakeniseenvoudigScroloml(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 14.0,
                              right: null,
                              bottom: null,
                              width: 68.0,
                              height: 68.0,
                              child: GeneratedRectangle29Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
