import 'package:flutter/material.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedgeroosterdewortelswidget/generated/GeneratedThuisgemaaktWidget8.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedgeroosterdewortelswidget/generated/GeneratedReclameWidget6.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedgeroosterdewortelswidget/generated/GeneratedInstructiesWortelenroosterenindeoveniseenvoudigScroloml.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedgeroosterdewortelswidget/generated/GeneratedIngredintenWortelenDewortelendieopdemarktwordengebracht.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedgeroosterdewortelswidget/generated/GeneratedGEROOSTERDEWORTELSWidget1.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedgeroosterdewortelswidget/generated/GeneratedMaaralsjedienietkuntvindenishetprimaomgewonewortelenteg.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedgeroosterdewortelswidget/generated/GeneratedRectangle25Widget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedgeroosterdewortelswidget/generated/GeneratedRectangle6Widget8.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedgeroosterdewortelswidget/generated/GeneratedRectangle27Widget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedgeroosterdewortelswidget/generated/GeneratedRectangle24Widget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedgeroosterdewortelswidget/generated/GeneratedRectangle26Widget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedgeroosterdewortelswidget/generated/GeneratedRectangle29Widget3.dart';

/* Frame GEROOSTERDE WORTELS
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGEROOSTERDEWORTELSWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 2321.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 925.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 430.0,
                              height: 82.0,
                              child: GeneratedRectangle6Widget8(),
                            ),
                            Positioned(
                              left: 119.0,
                              top: 21.0,
                              right: null,
                              bottom: null,
                              width: 249.0,
                              height: 49.0,
                              child: GeneratedThuisgemaaktWidget8(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 97.0,
                              right: null,
                              bottom: null,
                              width: 307.0,
                              height: 86.0,
                              child: GeneratedGEROOSTERDEWORTELSWidget1(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 181.0,
                              right: null,
                              bottom: null,
                              width: 406.0,
                              height: 184.0,
                              child:
                                  GeneratedIngredintenWortelenDewortelendieopdemarktwordengebracht(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 372.0,
                              right: null,
                              bottom: null,
                              width: 394.0,
                              height: 263.0,
                              child: GeneratedRectangle24Widget(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 688.0,
                              right: null,
                              bottom: null,
                              width: 296.0,
                              height: 600.0,
                              child:
                                  GeneratedMaaralsjedienietkuntvindenishetprimaomgewonewortelenteg(),
                            ),
                            Positioned(
                              left: 56.0,
                              top: 1516.0,
                              right: null,
                              bottom: null,
                              width: 322.0,
                              height: 242.0,
                              child: GeneratedRectangle25Widget(),
                            ),
                            Positioned(
                              left: 52.0,
                              top: 1314.0,
                              right: null,
                              bottom: null,
                              width: 326.0,
                              height: 174.0,
                              child: GeneratedRectangle27Widget(),
                            ),
                            Positioned(
                              left: 53.0,
                              top: 1773.0,
                              right: null,
                              bottom: null,
                              width: 352.0,
                              height: 340.0,
                              child:
                                  GeneratedInstructiesWortelenroosterenindeoveniseenvoudigScroloml(),
                            ),
                            Positioned(
                              left: 56.0,
                              top: 2139.0,
                              right: null,
                              bottom: null,
                              width: 322.0,
                              height: 182.0,
                              child: GeneratedRectangle26Widget(),
                            ),
                            Positioned(
                              left: 179.0,
                              top: 1488.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 31.0,
                              child: GeneratedReclameWidget6(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 20.0,
                              right: null,
                              bottom: null,
                              width: 68.0,
                              height: 68.0,
                              child: GeneratedRectangle29Widget3(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}

mixin Overflow {}
