import 'package:flutter/material.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedkokosbloempannekoekenwidget/generated/GeneratedRectangle23Widget.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedkokosbloempannekoekenwidget/generated/GeneratedKOKOSBLOEMPANNEKOEKENWidget1.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedkokosbloempannekoekenwidget/generated/GeneratedRectangle21Widget1.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedkokosbloempannekoekenwidget/generated/GeneratedRectangle6Widget7.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedkokosbloempannekoekenwidget/generated/GeneratedRectangle20Widget1.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedkokosbloempannekoekenwidget/generated/GeneratedInstructiesDezepannenkoekenvankokosmeelmaakjeheelmakkel.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedkokosbloempannekoekenwidget/generated/GeneratedIngredintenJehebtmaareenpaarsimpeleingredintennodigomde1.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedkokosbloempannekoekenwidget/generated/GeneratedRectangle28Widget3.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedkokosbloempannekoekenwidget/generated/GeneratedReclameWidget5.dart';
import 'package:flutterapp/foodthuisgemaaktapp/generatedkokosbloempannekoekenwidget/generated/GeneratedThuisgemaaktWidget7.dart';

/* Frame KOKOSBLOEM PANNEKOEKEN
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKOKOSBLOEMPANNEKOEKENWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 2687.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 923.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 430.0,
                              height: 82.0,
                              child: GeneratedRectangle6Widget7(),
                            ),
                            Positioned(
                              left: 119.0,
                              top: 21.0,
                              right: null,
                              bottom: null,
                              width: 249.0,
                              height: 49.0,
                              child: GeneratedThuisgemaaktWidget7(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 97.0,
                              right: null,
                              bottom: null,
                              width: 434.0,
                              height: 126.0,
                              child: GeneratedKOKOSBLOEMPANNEKOEKENWidget1(),
                            ),
                            Positioned(
                              left: 10.0,
                              top: 201.0,
                              right: null,
                              bottom: null,
                              width: 406.0,
                              height: 1068.0,
                              child:
                                  GeneratedIngredintenJehebtmaareenpaarsimpeleingredintennodigomde1(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 1500.0,
                              right: null,
                              bottom: null,
                              width: 404.0,
                              height: 346.0,
                              child: GeneratedRectangle20Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 1873.0,
                              right: null,
                              bottom: null,
                              width: 383.0,
                              height: 470.0,
                              child:
                                  GeneratedInstructiesDezepannenkoekenvankokosmeelmaakjeheelmakkel(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 1308.0,
                              right: null,
                              bottom: null,
                              width: 381.0,
                              height: 151.0,
                              child: GeneratedRectangle21Widget1(),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 2368.0,
                              right: null,
                              bottom: null,
                              width: 371.0,
                              height: 319.0,
                              child: GeneratedRectangle23Widget(),
                            ),
                            Positioned(
                              left: 176.0,
                              top: 1472.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 31.0,
                              child: GeneratedReclameWidget5(),
                            ),
                            Positioned(
                              left: 23.0,
                              top: 14.0,
                              right: null,
                              bottom: null,
                              width: 68.0,
                              height: 68.0,
                              child: GeneratedRectangle28Widget3(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
